name: 'Vault'
version: ${plugin.version}
description: 'Vault is a Permissions & Economy API to allow plugins to more easily hook into these systems without needing to hook each individual system themselves.'
website: 'https://github.com/egg82/FastVault'
api-version: 1.13

authors:
  - 'cereal'
  - 'Sleaker'
  - 'mung3r'
  - 'egg82'

softdepend:
# Permissions
  - 'bPermissions'
  - 'DroxPerms'
  - 'GroupManager'
  - 'KPerms'
  - 'LuckPerms'
  - 'OverPermissions'
  - 'Permissions'
  - 'PermissionsBukkit'
  - 'PermissionsEx'
  - 'Privileges'
  - 'rscPermissions'
  - 'SimplyPerms'
  - 'TotalPermissions'
  - 'vPerms'
  - 'Xperms'
# Economy
  - 'CommandsEx'

main: 'net.milkbowl.vault.Vault'
load: 'STARTUP'

commands:
  vault-info:
    description: 'Displays information about Vault '
    usage: |
           /<command> - Displays Vault information
    permission: 'vault.admin'
  vault-convert:
    description: 'Converts all data in economy1 and dumps it into economy2'
    usage: |
           /<command> [economy1] [economy2]
    permission: 'vault.admin'

permissions:
  vault.admin:
    description: 'Notifies the player when vault is in need of an update.'
    default: op